### ISSUE TITLE
Confusion about this core

### ISSUE THREAD

**Issue by ghost** [opengateware/arcade-bankp#1]
### Ask a question about Green Beret Compatible Gateware IP Core

Hi,
Good job on the port.
Reading the README, it is very confusing as to if this is a work by Pierre or by you. Since this is a port of the MiSTer FPGA core. Maybe it is better if you can specify it. Same thing can be said with the other cores that you have ported from MiSTer
Kind regards

**Comment by boogermann** [comment]
It's literally the first line of the readme other then the title
> This Implementation of a compatible Bank Panic arcade hardware in HDL is the work of [Pierre Cornier](https://github.com/pcornier).

All cores are the same thing, I give credit to who created the core in the first line and the people who worked on it or the dependencies on _Credits and acknowledgment_.

The RTL is not platform bound, nor the code is using the MiSTer framework.

**Comment by boogermann** [comment]
Just to make clear, I do not list projects in the readme since the projects do not inherently contribute to the core, developers do. If I did, I'd have to list all of the various projects that have used the code, including OpenFPGA and that does not make a lot of sense since they did not contribute.

**Comment by ghost** [comment]
That is fine, my point is that since this is a port, it should be mentioned in the read-me or at least rewritten "This Implementation of a compatible Bank Panic arcade hardware in HDL is the work of [Pierre Cornier](https://github.com/pcornier)." I want to know from which repo the code is coming and it would be better if you could link it. Just a suggestion

**Comment by boogermann** [comment]
That is also always listed and linked!

## Powered by Open-Source Software

This project borrowed and use code from several other projects. A great thanks to their efforts!

| Modules                                                      | Copyright/Developer      |
| ------------------------------------------------------------ | ------------------------ |
| [Bank Panic RTL](https://github.com/MiSTer-devel/Arcade-BankPanic_MiSTer/tree/master/rtl) | 2013 (c) Pierre Cornier  |
| [TV80](https://github.com/hutch31/tv80)                      | 2004 (c) Guy Hutchison   |
| [SN76489](https://github.com/dnotq/sn76489_audio)            | 2020 (c) Matthew Hagerty |
